# # ç«™ç‚¹åŸºç¡€ä¿¡æ¯ï¼ˆå¿…å¡«ï¼Œæ”¹æˆä½ çš„ï¼‰
# title: x_yeyueçš„åšå®¢  # åšå®¢æ ‡é¢˜
# subtitle: ç”¨Yunä¸»é¢˜æ­å»ºçš„ç®€çº¦åšå®¢  # å‰¯æ ‡é¢˜ï¼ˆå¯é€‰ï¼‰
# author: x_yeyue  # ä½ çš„æ˜µç§°
# language: zh-CN  # è¯­è¨€æ”¹æˆä¸­æ–‡
# timezone: Asia/Shanghai  # æ—¶åŒºï¼ˆä¸­å›½æ—¶åŒºï¼‰

# # å¯¼èˆªæ ï¼ˆå¸¸ç”¨é“¾æ¥ï¼ŒæŒ‰éœ€åŠ /åˆ ï¼‰
# menu:
#   é¦–é¡µ: /
#   å½’æ¡£: /archives/
#   å…³äºæˆ‘: /about/

# # å¤´åƒï¼ˆå¯é€‰ï¼Œæ›¿æ¢æˆä½ çš„å›¾ç‰‡é“¾æ¥ï¼Œæœ¬åœ°å›¾ç‰‡æ”¾ source/images/ é‡Œï¼Œå†™ /images/å¤´åƒ.jpg å³å¯ï¼‰
# avatar: 
#   url: /images/avatar.jpg
#   rounded: true
#   opacity: 1

# # é¡µè„šä¿¡æ¯ï¼ˆå¯é€‰ï¼‰
# footer:
#   text: ç‰ˆæƒæ‰€æœ‰ Â© 2026 x_yeyue  # é¡µè„šæ–‡å­—
mode: auto

avatar:
  url: /images/avatar.jpg
  status:
    enable: true
    emoji: ğŸŒ‘
    message: Looking for dawn.

reward:
  enable: true
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: æ”¯ä»˜å®
      path: None # https://cdn.yunyoujun.cn/img/donate/alipay-qrcode.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: None # https://cdn.yunyoujun.cn/img/donate/qqpay-qrcode.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: None # https://cdn.yunyoujun.cn/img/donate/wechatpay-qrcode.jpg
      color: '#2DC100'
      icon: ri:wechat-pay-line

# comment:
#   candidates:
#     - waline
#     # - giscus
#   tips:
#     - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿å‰å¾€ <a href="https://github.com/YunYouJun/yunyoujun.github.io/discussions" target="_blank">GitHub Discussions</a> ä¸æˆ‘äº¤æµã€‚

waline:
  enable: true
  # serverURL: https://waline.yunyoujun.cn
  visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/qq/
  locale:
    placeholder: å¡«å†™é‚®ç®±ï¼Œå¯ä»¥æ”¶åˆ°å›å¤é€šçŸ¥å“¦ï½
  requiredMeta: [nick]

github_issues:
  enable: false

github_discussions:
  enable: false

# disqusjs:
#   enable: false
#   shortname: yunyoujun
#   apikey: ouoGQCaamOKdJgyZU5DKcpFnRIg3SNzvk0nwygPtlcTRJuE68c8igvrZGW4wAJoN

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: x-yeyue/x-yeyue.github.io # YunYouJun/yunyoujun.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

# footer:
#   since: 2016
#   icon:
#     url: https://sponsors.yunyoujun.cn
#     title: äº‘æ¸¸å›çš„èµåŠ©è€…ä»¬
#   beian:
#     enable: true
#     icp: è‹ICPå¤‡17038157å·
#   support:
#     enable: true
#     title: åˆæ‹äº‘
#     link: https://www.upyun.com
#     logo: https://cdn.yunyoujun.cn/img/logo/upyun-logo.png
#     prefix: æœ¬ç½‘ç«™ç”±
#     suffix: æä¾› CDN åŠ é€Ÿ
#   custom_text:

engine_search:
  enable: false


# google_analytics:
#   enable: true
#   id: G-1LL0D86CY9

# google_adsense:
#   enable: true
#   client: ca-pub-2245427233262012

# post_edit:
#   enable: true
#   url: https://github.com/YunYouJun/yunyoujun.github.io/tree/hexo/source/

albums:
  enable: true

girls:
  enable: true

tags:
  åŠ¨ç”»: crimson
  æ¼«ç”»: orange
  Parcel: '#21374b'
  å­¦ä¹ : saddlebrown
  MAD: crimson
  æ•™ç¨‹: royalblue
  ç¬”è®°: dimgray
  åˆ†äº«: '#0078e7'
  éšç¬”: mediumpurple
  Blender: '#d04d2d'
  Linux: '#2577b1'
  ä¸­ä¼ : '#ccb44b'
  éƒ¨è½: '#DD306A'
  ç§‘å¹»: midnightblue
  èš‚èšæ£®æ—: '#54a892'

categories:
  äº‘æ¸¸çš„å°è§†é¢‘: '#FB7299'

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: None
    url: None
    icon: ri:women-line
    color: hotpink

menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: ri:clipboard-line

cursor:
  enable: true

baidu_push: true

google_tagmanager:
  enable: true
  id: GTM-M9KWR9L

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

social:
  - name: GitHub
    link: https://github.com/x-yeyue
    icon: ri:github-line
    color: '#6e5494'
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/2145646692
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: E-Mail
    link: mailto:3482199229@qq.com
    icon: ri:mail-line
    color: '#8E71C1'
# pjax:
#   enable: true
